#My First Pipeline for RG.

name: RG_pipeline

trigger: none

pool: pool1

parameters:
  - name: runInit
    type: boolean
    default: true

  - name: runValidate
    type: boolean
    default: true

  - name: runPlan
    type: boolean
    default: true
  
  - name: runApply
    type: boolean
    default: true

  - name: runShow
    type: boolean
    default: true


steps:

- task: TerraformTask@5
  displayName: Azure_init
  condition: eq('${{ parameters.runInit }}', true)
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'serviceconnectionab'
    backendAzureRmResourceGroupName: 'backend'
    backendAzureRmStorageAccountName: 'abackend'
    backendAzureRmContainerName: 'backend'
    backendAzureRmKey: 'bknd.tfstate'

- task: TerraformTask@5
  displayName: Azure_validate
  condition: eq('${{ parameters.runValidate }}', true)
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  displayName: Azure_plan
  condition: eq('${{ parameters.runPlan }}', true)
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'serviceconnectionab'

- task: TerraformTask@5
  displayName: Azure_apply
  condition: eq('${{ parameters.runApply }}', true)
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '--auto-approve'
    environmentServiceNameAzureRM: 'serviceconnectionab'

- task: TerraformTask@5
  displayName: Azure_show
  condition: eq('${{ parameters.runShow }}', true)
  inputs:
    provider: 'azurerm'
    command: 'show'
    outputTo: 'console'
    outputFormat: 'default'
    environmentServiceNameAzureRM: 'serviceconnectionab'
